package com.example.intermediaries.entities.registrations;

import com.example.intermediaries.entities.intermediariesinfo.IntermediaryTypes;
import jakarta.persistence.*;

@Table
@Entity
public class ParentIntermediaries {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    private String title ;

    @ManyToOne()
    @JoinColumn(name = "FK_intermediaryTypesId", referencedColumnName = "id")
    private IntermediaryTypes intermediaryType;

    public Integer getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

// autogenerated title from selected type id (type title + id)
    public void setTitle() {

            this.title = getIntermediaryType().getIntermidiaryType() +
                    "" + getId();

    }

    public IntermediaryTypes getIntermediaryType() {
        return intermediaryType;
    }

    public void setIntermediaryType(IntermediaryTypes intermediaryType) {
        this.intermediaryType = intermediaryType;
    }
}
