package com.example.intermiteries.registrations;

import com.example.intermiteries.info.IntermidiaryTypes;
import com.example.intermiteries.info.TypeOfIntermidiary;
import jakarta.persistence.*;

@Table
@Entity
public class ParentIntermediaries {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    private String title ;

    @ManyToOne()
    @JoinColumn(name = "FK_intermidiaryTypesId", referencedColumnName = "id")
    private IntermidiaryTypes intermidiaryType;

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

// autogenerated title from selected type id (type title + id)
    public void setTitle() {
        this.title = getIntermidiaryType().getIntermidiaryType() +
                "" + getId();
    }

    public IntermidiaryTypes getIntermidiaryType() {
        return intermidiaryType;
    }

    public void setIntermidiaryType(IntermidiaryTypes intermidiaryType) {
        this.intermidiaryType = intermidiaryType;
    }
}
